name: Update Kustomize Image

on:
  workflow_call:
    inputs:
      manifests_repo:
        required: true
        type: string
      manifests_path:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      service_name:
        required: true
        type: string
    secrets:
      K8S_REPO_TOKEN:
        required: true

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.manifests_repo }}
          token: ${{ secrets.K8S_REPO_TOKEN }}
          path: k8s-manifests

      - name: Update kustomization.yaml
        run: |
          cd k8s-manifests/${{ inputs.manifests_path }}
          yq -i ".images[0].newTag = \"${{ inputs.image_tag }}\"" kustomization.yaml

      - name: Commit and push
        run: |
          cd k8s-manifests

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Update ${{ inputs.service_name }} image to ${{ inputs.image_tag }}"
          git push
